repository:
  # A short description of the repository that will show up on GitHub
  description: you should really provide a better description

  # A URL with more information about the repository
  homepage: https://www.psg.fr/
  
  # Either `true` to make the repository private, or `false` to make it public.
  private: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Updates the default branch for this repository.
  default_branch: main

# Labels: define labels for Issues and Pull Requests
labels:
  - name: PSG
    color: CC0000
  - name: beats
    color: 336699
  - name: Bayern
    # include the old name to rename and existing label
    oldname: Help Wanted

# Collaborators: give specific users access to this repository.
collaborators:
  - username: bkeepers
    # Note: Only valid on organization-owned repositories.
    # The permission to grant the collaborator. Can be one of:
    # * `pull` - can pull, but not push to or administer this repository.
    # * `push` - can pull and push, but not administer this repository.
    # * `admin` - can pull, push and administer this repository.
    permission: push

  - username: hubot
    permission: pull

  - username:
    permission: pull
