repository:
  # A short description of the repository that will show up on GitHub
  description: you should really provide a better description

  # A URL with more information about the repository
  homepage: https://www.psg.fr/
  
  # Either `true` to make the repository private, or `false` to make it public.
  private: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Updates the default branch for this repository.
  default_branch: main

# Labels: define labels for Issues and Pull Requests
labels:
  - name: PSG
    color: CC0000
  - name: beats
    color: 336699
  - name: Bayern
    # include the old name to rename and existing label
    oldname: Help Wanted
  - name: needs-more-info
    color: FF0000
